# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76408a963216cd1919f6ba29310b6f61334ce56b5ca2290d708b9b747e5ac29c4ec815f52e9efb7fdd8b1655b1718e51f655a0f18d6b29dad973b776b1087aa9

test:
  secret_key_base: 2f4f9088f575c8caf007685a515554c1884946c503e2e72bfeb087fcedf4fbbb82686b6fd3f4449315963558623c52776c390aedc5921abacaff6f8a25e63a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
